---
- name: Pull Image
  hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo
  - debug:
      msg "tag is" {{TAG}}
  roles:
   - { role: Dockerclean }
   - { role: network }
   - { role: repologin }
   - { role: repopull }
   - { role: dbapp_install }   
   - { role: webapp_install }
...