---
- name: Pull Image
  vars:
   - env: "dev"
   - docktag: "dev"
  hosts: {{env}}
  remote_user: ec2-user
  become: yes
  become_method: sudo
  roles:
   - { role: Dockerclean }
   - { role: network }
   - { role: repologin }
   - { role: repopull }
   - { role: dbapp_install }   
   - { role: webapp_install }
...