---
- name: delete container
  docker_container:
    name: dbapp
    state: absent
    
- name: delete webapp    
  docker_container:
    name: webapp
    state: absent
    
- name: Delete a network, disconnecting all containers
  docker_network:
    name: network_one
    state: absent
    force: yes

- name: delete image
  docker_image:
    name: docker.donemmerson.co.uk:443/usrsignup
    tag: latest
    state: absent

- name: delete image
  docker_image:
    name: docker.donemmerson.co.uk:443/usrdb
    tag: latest
    state: absent
    
    