---
- name: Create a webserver
  docker_container:
    name: webapp
    image: docker.donemmerson.co.uk:443/usrsignup:latest
    state: started
    exposed_ports:
      - 8080
    published_ports: 
      - "8080:8080"
    networks: 
      - name: network_one
    links:
      - "dbapp:database"
