---
- name: Re-create a db container
  docker_container:
    name: dbapp
    image: docker.donemmerson.co.uk:443/usrdb:latest
    state: started
    exposed_ports:
      - 3306
    published_ports: 
      - "3306:3306"
    networks: 
      - name: network_one
    