---
- name: pull dbapp
- debug:
     msg "tag is" {{TAG}}
  docker_image:
    repository: docker.donemmerson.co.uk:443/usrdb
    name: docker.donemmerson.co.uk:443/usrdb
    tag: "{{ TAG }}"
    state: present
    
- name: pull webapp
  docker_image:
    repository: docker.donemmerson.co.uk:443/usrsignup
    name: docker.donemmerson.co.uk:443/usrsignup
    tag: "{{ TAG }}"
    state: present